export enum AccessRequestStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  MORE_INFORMATION_REQUIRED = 'MORE_INFORMATION_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum AssignedRole {
  CYBER_CELL_ADMIN = 'CYBER_CELL_ADMIN',
  SENIOR_INVESTIGATOR = 'SENIOR_INVESTIGATOR',
  INVESTIGATOR = 'INVESTIGATOR',
  ANALYST = 'ANALYST',
  AUDITOR = 'AUDITOR',
}
