import { FC } from "react";

export const SecurityNotice: FC = () => {
  return (
    <div className="auth-security-notice">
      OFFICIAL USE ONLY. ACCESS TO SANDHAAN IS RESTRICTED TO AUTHORIZED LAW ENFORCEMENT &amp; SECURITY PERSONNEL.
      ALL ACCESS ATTEMPTS AND AUTHENTICATED ACTIVITIES ARE MONITORED, CRYPTOGRAPHICALLY SIGNED, AND AUDITED UNDER
      THE INFORMATION TECHNOLOGY ACT, 2000 AND OFFICIAL SECRETS ACT, 1923.
    </div>
  );
};
